### ISSUE TITLE
Toposort module required by create_lec_tests.sh

### ISSUE THREAD

**Issue by veinamond** [Vikseko/Circuit2cnf-gen#1]
Hey, Victor!
I was trying out your generator, and it was all good, until I ran create_lec_tests.sh script in the Multipliers_lec folder, where it promptly informed me that no module named 'toposort' was found. 
I think it would be nice if you could list this requirement in the Readme.
Hope this helps!

**Comment by Vikseko** [comment]
Updated the readme to make it clearer.
