### ISSUE TITLE
No aags for multipliers other than 12x12

### ISSUE THREAD

**Issue by veinamond** [Vikseko/Circuit2cnf-gen#2]
Hello!
I am testing the generator and stumbled upon the issue when I wanted to generate multiplier LEC benchmarks for 10x10 and 11x11.
The LEC generation script for some reason can not generate multiplier AAGs by itself - I need to work around and first launch the create_tests.sh in the Multipliers folder. 
Can you please fix this behavior?

**Comment by veinamond** [comment]
come to think of it, I might have first run the script in the Multiplier folder for 12x12. Anyway, this is not intuitive, and I would appreciate if you could fix that

**Comment by Vikseko** [comment]
Added the ability to build "all at once" for a separate class of problems from the main directory.
